Repository puppetlabs/dependency_checker, pull requests merged in 2023-04, with the labels that each got.

#37 pdksync - (Maint) - Update nightly.yml
  .github/workflows/nightly.yml
Labels: maintenance

#38 (CONT-810) Ruby 3 support
  .bumpversion.cfg
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .rubocop.yml
  .rubocop_todo.yml
  .travis.yml
  Gemfile
  bin/dependency-checker
  dependency_checker.gemspec
  lib/dependency_checker/forge_helper.rb
  lib/dependency_checker/metadata_checker.rb
  lib/dependency_checker/runner.rb
  spec/unit/forge_helper_spec.rb
  spec/unit/metadata_checker.rb
  spec/unit/runner_spec.rb
Labels: backwards-incompatible

#40 (MAINT) Ignore vendor directory
  .gitignore
Labels: maintenance

#45 (MAINT) Revert version string
  lib/dependency_checker/version.rb
Labels: bugfix, maintenance
